runtime: python37
entrypoint: gunicorn -b $PORT main:app

runtime_config:
    python_version: 3
    
# setting it as cheap as possible b/c I am poor 
automatic_scaling:
    max_instances: 1
    min_instances: 0
    min_idle_instances: 0
    max_idle_instances: 1
    target_cpu_usage: 0.95